# Generated by Django 3.2.7 on 2021-09-19 19:23

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('registration', 'Регистрация'), ('top_up_balance', 'Пополнение баланса')], max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('declined', 'Отказано'), ('processing', 'В рассмотрении')], default='processing', max_length=25)),
                ('comment', models.TextField(blank=True, null=True)),
                ('request_info', models.TextField(blank=True, null=True)),
                ('info', jsonfield.fields.JSONField(blank=True, editable=False, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Franсhise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('bin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalePointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='client.salepointtype')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('telegram_id', models.IntegerField(blank=True, default=-1, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('royalty', models.IntegerField(blank=True, default=50, null=True)),
                ('royalty_expires', models.DateField(blank=True, null=True)),
                ('requisites', models.CharField(default=0, max_length=512)),
                ('info', jsonfield.fields.JSONField(blank=True, editable=False, null=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise', to='client.franсhise')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.role')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('up', 'Пополнение'), ('down', 'Списание')], max_length=64)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchisee', to='client.franсhise')),
            ],
        ),
    ]
