from aiogram import types


register_query = types.InlineKeyboardButton('Регистрация', callback_data="register_query")
faq_query = types.InlineKeyboardButton('FAQ', callback_data="faq_query")
payment_query = types.InlineKeyboardButton("Запросить счет на оплату", callback_data="payment_query")
sale_point_query = types.InlineKeyboardButton("Пополнение торговой точки", callback_data="sale_point_query")
sale_point = types.InlineKeyboardButton("Торговая точка", callback_data="sale_point")
balance_query = types.InlineKeyboardButton("Проверить баланс", callback_data="balance_query")
top_up_balance_query = types.InlineKeyboardButton("Пополнение баланса", callback_data="top_up_balance_query")
balance_history_query = types.InlineKeyboardButton("История баланса", callback_data="balance_history_query")
promotion_terms_query = types.InlineKeyboardButton("Условия и правила акции", callback_data="promotion_terms_query")
promotion_apply_query = types.InlineKeyboardButton("Подать заявку на акцию", callback_data="promotion_apply_query")
sale_point_activation_query = types.InlineKeyboardButton("Активация торговой точки",
                                                         callback_data="sale_point_activation_query")
promotion_suggestion_query = types.InlineKeyboardButton("Предложения о торговой точки",
                                                        callback_data="promotion_suggestion_query")
feedback_query = types.InlineKeyboardButton("Обратная связь", callback_data="feedback_query")
solution_reference_query = types.InlineKeyboardButton("Справочник решений", callback_data="solution_reference_query")
report_bug_query = types.InlineKeyboardButton("Оформить баг", callback_data="report_bug_query")
balance = types.InlineKeyboardButton("Баланс", callback_data="balance")
promotion = types.InlineKeyboardButton("Акция", callback_data="promotion")
yes_query = types.InlineKeyboardButton("Одобрено", callback_data="YES")
no_query = types.InlineKeyboardButton("Отказано", callback_data="NO")
exit = types.InlineKeyboardButton("Меню", callback_data="exit")
buttons = [payment_query, sale_point, balance, promotion, feedback_query, faq_query
               ]
owner_keyboard = types.InlineKeyboardMarkup()
for button in buttons:
    owner_keyboard.row(button)
register_keyboard = types.InlineKeyboardMarkup()
register_keyboard.row(register_query)
technical_specialist_keyboard = types.InlineKeyboardMarkup()
technical_specialist_keyboard.row(report_bug_query)
technical_specialist_keyboard.row(faq_query)
technical_specialist_keyboard.row(solution_reference_query)
technical_specialist_keyboard.row(feedback_query)
technical_specialist_keyboard.row(exit)
yes_no_keyboard = types.InlineKeyboardMarkup()
yes_no_keyboard.row(yes_query, no_query)
promotion_keyboard = types.InlineKeyboardMarkup()
promotion_keyboard.row(promotion_terms_query)
promotion_keyboard.row(promotion_apply_query)
promotion_keyboard.row(exit)
balance_keyboard = types.InlineKeyboardMarkup()
balance_keyboard.row(balance_query)
balance_keyboard.row(top_up_balance_query)
balance_keyboard.row(balance_history_query)
balance_keyboard.row(exit)
sale_point_keyboard = types.InlineKeyboardMarkup()
sale_point_keyboard.row(sale_point_query)
sale_point_keyboard.row(sale_point_activation_query)
sale_point_keyboard.row(promotion_suggestion_query)
sale_point_keyboard.row(exit)
